spring:
  datasource:
    url: jdbc:mysql://metroo-server.mysql.database.azure.com:3306/product_service?useSSL=true
    username: arkam
    password: Arkam@4169
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
server:
  port: 8080
